# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).

user1 = User.create(name: "Albert", email: "albert@albert.com")
user2 = User.create(name: "Kris", email: "kris@grandma.com")
user3 = User.create(name: "Jamal", email: "jama@grandma.com")
user4 = User.create(name: "Edwin", email: "edwin@grandma.com")
user5 = User.create(name: "Stacey1", email: "mega@grandma.com")
user6 = User.create(name: "Bigfoot", email: "bigfoot@grandma.com")
byebug
event1 = Event.create(title: "My FUn Event", description: "Come and have some fun now!", address: "ur mom's house", date: Time.zone.parse("2018-11-15"), user_id: 1)
event2 = Event.create(title: "bouncy castle & beer", description: "bounce and buzz", address: "Mr HAppy's Castle", date: Time.zone.parse("2018-11-19"), user_id: 2)
event3 = Event.create(title: "Drink a shit ton of alcohol an make a total ass out of yourself", description: "regret it every time but youll keep coming back", address: "my parent's basement. dont wake them up pls", date: Time.zone.parse("2018-11-16"), user_id: 3)
attendance1 = Attendance.create(user_id: 1, event_id: 1)
attendance2 = Attendance.create(user_id: 2, event_id: 1)
attendance3 = Attendance.create(user_id: 3, event_id: 1)
attendance4 = Attendance.create(user_id: 4, event_id: 1)
attendance4 = Attendance.create(user_id: 5, event_id: 1)
attendance4 = Attendance.create(user_id: 6, event_id: 1)
attendance1 = Attendance.create(user_id: 1, event_id: 2)
attendance2 = Attendance.create(user_id: 2, event_id: 2)
attendance3 = Attendance.create(user_id: 3, event_id: 2)
attendance4 = Attendance.create(user_id: 4, event_id: 2)
attendance4 = Attendance.create(user_id: 5, event_id: 2)
attendance4 = Attendance.create(user_id: 6, event_id: 2)
attendance1 = Attendance.create(user_id: 1, event_id: 3)
attendance2 = Attendance.create(user_id: 2, event_id: 3)
attendance3 = Attendance.create(user_id: 3, event_id: 3)
attendance4 = Attendance.create(user_id: 4, event_id: 3)
attendance4 = Attendance.create(user_id: 5, event_id: 3)
attendance4 = Attendance.create(user_id: 6, event_id: 3)
